import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import helmet from 'helmet';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import { fullClientAssetsRouter,FULL_CLIENT_ASSET_PATH,FULL_CLIENT_ASSET_SHA256 } from './full-client-assets.ts';
async function server(router:express.Router,run:(base:string)=>Promise<void>){const app=express();app.use(helmet());app.use('/v1',router);const s=app.listen(0,'127.0.0.1');await new Promise<void>(r=>s.once('listening',r));try{await run(`http://127.0.0.1:${(s.address() as {port:number}).port}/v1`);}finally{await new Promise<void>((r,j)=>s.close(e=>e?j(e):r()));}}
test('public exact version helper has pinned bytes/type/cache and executable VM surface',async()=>server(fullClientAssetsRouter(),async base=>{const response=await fetch(base+FULL_CLIENT_ASSET_PATH,{headers:{Origin:'https://joyous-trellis-editor.weweb.io'}});assert.equal(response.headers.get('cross-origin-resource-policy'),'cross-origin');assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'application/javascript; charset=utf-8');assert.equal(response.headers.get('cache-control'),'public, max-age=31536000, immutable');assert.equal(response.headers.get('x-content-type-options'),'nosniff');const text=await response.text();assert.equal(createHash('sha256').update(text).digest('hex'),FULL_CLIENT_ASSET_SHA256);const sb:any={};vm.createContext(sb);vm.runInContext(text,sb);assert.equal(sb.InvestScapeFullClient.targetCalculationPackageVersion,'0.10.0-p2-6b');assert.equal(Object.isFrozen(sb.InvestScapeFullClient),true);assert.equal(sb.InvestScapeFullClient.fullCalculate,undefined);assert.equal((await fetch(base+FULL_CLIENT_ASSET_PATH,{method:'HEAD'})).status,200);}));
test('missing/corrupt assets fail closed without cache or internal error',async()=>{for(const load of [()=>Buffer.from('bad'),()=>{throw new Error('privatepath');}])await server(fullClientAssetsRouter(load),async base=>{const response=await fetch(base+FULL_CLIENT_ASSET_PATH);assert.equal(response.status,503);assert.equal(response.headers.get('cache-control'),'no-store');assert.deepEqual(await response.json(),{error:{message:'Full client asset unavailable'}});});});
test('no arbitrary static directory/version/method routes',async()=>server(fullClientAssetsRouter(),async base=>{for(const url of ['/development/assets/full-client-1/full-client-build-manifest.json','/development/assets/full-client-2/'+FULL_CLIENT_ASSET_PATH.split('/').pop(),'/development/assets/full-client-1/../../vendor/secret'])assert.equal((await fetch(base+url)).status,404);assert.equal((await fetch(base+FULL_CLIENT_ASSET_PATH,{method:'POST'})).status,404);}));
test('manifest and sidecar match exact pinned source artifact',()=>{const root=new URL('../../../public/development/full-client-1/',import.meta.url);const manifest=JSON.parse(readFileSync(new URL('full-client-build-manifest.json',root),'utf8'));assert.equal(manifest.sha256,FULL_CLIENT_ASSET_SHA256);assert.equal(manifest.bytes,17483);assert.equal(manifest.targetCalculationPackageVersion,'0.10.0-p2-6b');assert.ok(readFileSync(new URL(manifest.artifact+'.sha256',root),'utf8').startsWith(FULL_CLIENT_ASSET_SHA256));});
