export const labels = {
    entryPending: {en: 'Your preferred module opens when you enter the app. Ribbon switching keeps the same address.', 'fr-CA': 'Votre module préféré s’ouvre à l’entrée dans l’app. Le ruban garde la même adresse.', 'zh-Hant': '進入應用程式時會開啟偏好的模組。切換功能列模組時網址維持不變。', 'zh-Hans': '进入应用程序时会打开偏好的模块。切换功能区模块时网址保持不变。'},
    start: {en: 'Preferred starting module', 'fr-CA': 'Module de départ préféré', 'zh-Hant': '偏好的起始模組', 'zh-Hans': '偏好的起始模块'},
    workspace: {en: 'Workspace', 'fr-CA': 'Espace de travail', 'zh-Hant': '工作區', 'zh-Hans': '工作区'},
    quick: {en: 'Quick Deal Analyzer', 'fr-CA': 'Analyse rapide de projet', 'zh-Hant': '專案快速分析', 'zh-Hans': '项目快速分析'},
    full: {en: 'Full Development Studio', 'fr-CA': 'Studio de développement complet', 'zh-Hant': '完整開發工作室', 'zh-Hans': '完整开发工作室'},
    library: {en: 'Library', 'fr-CA': 'Bibliothèque', 'zh-Hant': '知識庫', 'zh-Hans': '知识库'},
    portfolio: {en: 'Portfolio', 'fr-CA': 'Portefeuille', 'zh-Hant': '投資組合', 'zh-Hans': '投资组合'},
    'market-intel': {en: 'Market Intel', 'fr-CA': 'Veille de marché', 'zh-Hant': '市場情報', 'zh-Hans': '市场情报'},
    research: {en: 'Research', 'fr-CA': 'Recherche', 'zh-Hant': '研究', 'zh-Hans': '研究'},
    community: {en: 'Community', 'fr-CA': 'Communauté', 'zh-Hant': '社群', 'zh-Hans': '社区'},
    open: {en: 'Open preferred module', 'fr-CA': 'Ouvrir le module préféré', 'zh-Hant': '開啟偏好模組', 'zh-Hans': '打开偏好模块'},
    settings: {en: 'Global settings', 'fr-CA': 'Paramètres globaux', 'zh-Hant': '全站設定', 'zh-Hans': '全站设置'},
    language: {en: 'Language', 'fr-CA': 'Langue', 'zh-Hant': '語言', 'zh-Hans': '语言'},
    theme: {en: 'Appearance', 'fr-CA': 'Apparence', 'zh-Hant': '外觀', 'zh-Hans': '外观'},
    light: {en: 'Light', 'fr-CA': 'Clair', 'zh-Hant': '淺色', 'zh-Hans': '浅色'},
    dark: {en: 'Dark', 'fr-CA': 'Sombre', 'zh-Hant': '深色', 'zh-Hans': '深色'},
    country: {en: 'Home country', 'fr-CA': 'Pays principal', 'zh-Hant': '主要居住國家', 'zh-Hans': '主要居住国家'},
    canada: {en: 'Canada', 'fr-CA': 'Canada', 'zh-Hant': '加拿大', 'zh-Hans': '加拿大'},
    us: {en: 'United States', 'fr-CA': 'États-Unis', 'zh-Hant': '美國', 'zh-Hans': '美国'},
    currency: {en: 'Portfolio currency', 'fr-CA': 'Devise du portefeuille', 'zh-Hant': '投資組合貨幣', 'zh-Hans': '投资组合货币'},
    follow: {en: 'Follow home country', 'fr-CA': 'Selon le pays principal', 'zh-Hant': '依主要居住國家', 'zh-Hans': '按主要居住国家'},
    cad: {en: 'CAD — Canadian dollar', 'fr-CA': 'CAD — dollar canadien', 'zh-Hant': 'CAD — 加元', 'zh-Hans': 'CAD — 加元'},
    usd: {en: 'USD — US dollar', 'fr-CA': 'USD — dollar américain', 'zh-Hant': 'USD — 美元', 'zh-Hans': 'USD — 美元'},
    device: {en: 'These display preferences apply across this site and are saved on this device.', 'fr-CA': 'Ces préférences d’affichage s’appliquent à tout le site et sont enregistrées sur cet appareil.', 'zh-Hant': '這些顯示偏好適用於全站，並儲存在此裝置。', 'zh-Hans': '这些显示偏好适用于全站，并保存在此设备。'},
    scope: {en: 'Country and currency set defaults. Existing project amounts and jurisdictions stay as entered; Quick and Full do not convert currencies yet.', 'fr-CA': 'Le pays et la devise définissent les valeurs par défaut. Les montants et juridictions des projets existants restent inchangés; Quick et Full ne convertissent pas encore les devises.', 'zh-Hant': '國家與貨幣用於設定預設值。現有專案的金額與司法管轄區維持原有輸入；Quick 與 Full 尚未提供貨幣換算。', 'zh-Hans': '国家与货币用于设置默认值。现有项目的金额与司法管辖区保持原有输入；Quick 与 Full 尚未提供货币换算。'},
    selected: {en: 'Portfolio display currency', 'fr-CA': 'Devise d’affichage du portefeuille', 'zh-Hant': '投資組合顯示貨幣', 'zh-Hans': '投资组合显示货币'},
};
